name: fake-08

on:
  push:
    branches: '**'
  pull_request:
    branches: [ $default-branch ]

jobs:
  first:
    name: android-libretro
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules : recursive

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e

      - name: Build
      - runs: ndk-build NDK_PROJECT_PATH=platform/libretro/jni APP_BUILD_SCRIPT=platform/libretro/jni/Android.mk NDK_APPLICATION_MK=platform/libretro/jni/Application.mk

      - uses: actions/upload-artifact@v2
        with:
          name: Android
          path: |
            platform/libretro/arm64-v8a/*.so
            platform/libretro/armeabi-v7a/*.so