name: fake-08

on:
  push:
    branches: '**'
  pull_request:
    branches: [ $default-branch ]

jobs:
  first:
    name: android-libretro
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules : recursive

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e

      - name: Build
        run: cd platform/libretro/jni && ndk-build

      - uses: actions/upload-artifact@v2
        with:
          name: Android-arm64
          path: |
            arm64-v8a/*.so
            libs/arm64-v8a/*.so

      - uses: actions/upload-artifact@v2
        with:
          name: Android-arm
          path: |
            armeabi-v7a/*.so
            libs/armeabi-v7a/*.so